// Code generated by "stringer -type columnInfoStatus"; DO NOT EDIT.

package mssql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[columnInfoStatusExpression-4]
	_ = x[columnInfoStatusKey-8]
	_ = x[columnInfoStatusHidden-16]
	_ = x[columnInfoStatusDifferentName-32]
}

const (
	_columnInfoStatus_name_0 = "columnInfoStatusExpression"
	_columnInfoStatus_name_1 = "columnInfoStatusKey"
	_columnInfoStatus_name_2 = "columnInfoStatusHidden"
	_columnInfoStatus_name_3 = "columnInfoStatusDifferentName"
)

func (i columnInfoStatus) String() string {
	switch {
	case i == 4:
		return _columnInfoStatus_name_0
	case i == 8:
		return _columnInfoStatus_name_1
	case i == 16:
		return _columnInfoStatus_name_2
	case i == 32:
		return _columnInfoStatus_name_3
	default:
		return "columnInfoStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
